### ISSUE TITLE
Typo mistake.

### ISSUE THREAD

**Issue by kazinoman** [s-shemmee/Object-Oriebted-Programming-Concepts#1]
In the Object section, there ara a typo mistake in the second bullet point.

Objects are created with "specofoc" data.

Here the write word.
Objects are created with "specific" data.

**Comment by s-shemmee** [comment]
Thank you for bringing the typo to my attention! I have now fixed the mistake and updated the Object section. I appreciate you taking the time to let me know. Please let me know if you come across any other issues in the future. Have a great day!
